version: '3.8'

services:
  postgres-db:
    image: postgres:16.13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: dev_peapea
      POSTGRES_PASSWORD: dev01
      POSTGRES_DB: bootcamp_db2
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: