spring.application.name=rms-backend

# 1. URL
spring.datasource.url=jdbc:postgresql://localhost:5433/bootcamp_db
spring.datasource.username=dev_peapea
spring.datasource.password=password123

# 3. ?????????? Java
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect